### ISSUE TITLE
CH552G with bootloader 2.5.0

### ISSUE THREAD

**Issue by JustCryen** [frank-zago/isp55e0#11]
I have bought a device with a CH552G on bootloader version 2.5.0 and the dumped flash seems to be filled with F from offset 0x0 to 0x7F, no other data after that.

The device is a 3 key keyboard with a rotary encoder and does work when connected in non bootloader mode so I guess the flash is not dumped correctly.

Is that something that can be resolved?

**Comment by frank-zago** [comment]
Sorry, I have no idea.

**Comment by JustCryen** [comment]
I guess it's encrypted.  
I haven't returned to this project yet but I guess writing my own firmware for it will be a better solution.  

Thanks for making this tool, greatly appreciate that <3  

Issue can be closed if you don't plan on doing anything with encryption.

**Comment by frank-zago** [comment]
You can't read the flash code with the regular bootloader. There was a trick on older bootloaders, but that was closed in 2.4 I think.

**Comment by JustCryen** [comment]
Gotcha
