### ISSUE TITLE
is it ok to make patch, that allow disable libusb (and corresponding usb related functions)?

### ISSUE THREAD

**Issue by nikitos1550** [frank-zago/isp55e0#19]
Hi ! 

How do you think can you accept patch that allow disable usb functions?
I need this for embedded env, as now I need put libusb to rootfs, while actually I am not using this at all.

Something like -DLIBUSB_DISABLE

**Comment by frank-zago** [comment]
Yes, but I'd prefer something like 
#if WITH_USB
...
#endif

with WITH_USB being set by default.
In the Makefile:
WITH_USB ?= 1
CFLAGS += -DWITH_USB=${WITH_USB}

then to disable it during the build:  make WITH_USB=0
